development:
  adapter: postgresql
  database: known_db-dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: known_db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: known_db_prod
  pool: 5
  timeout: 5000
